apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: music-classifier
type: Opaque
stringData:
  SPRING_DATASOURCE_WRITE_USERNAME: "postgres"
  SPRING_DATASOURCE_WRITE_PASSWORD: "pass"
  SPRING_DATASOURCE_READ_USERNAME: "postgres"
  SPRING_DATASOURCE_READ_PASSWORD: "pass"
  SPRING_RABBITMQ_USERNAME: "rabbit"
  SPRING_RABBITMQ_PASSWORD: "pass"
  JWT_SECRET: "thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd"
  AWS_S3_CREDENTIALS_ACCESSKEY: "test"
  AWS_S3_CREDENTIALS_SECRETKEY: "test"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: music-classifier
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: music-classifier
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "rabbit"
  RABBITMQ_DEFAULT_PASS: "pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: music-classifier
type: Opaque
stringData:
  AWS_ACCESS_KEY: "test"
  AWS_SECRET_KEY: "test"

---
apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
  namespace: music-classifier
type: Opaque
stringData:
  RABBITMQ_USERNAME: "rabbit"
  RABBITMQ_PASSWORD: "pass"
  AWS_ACCESS_KEY: "test"
  AWS_SECRET_KEY: "test"